//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AnswerId { get; set; }
        public int UserId { get; set; }
        public int RiddleId { get; set; }
        public string UserAnswer { get; set; }
        public bool AnswerCheck { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
    
        public virtual Riddles Riddles { get; set; }
        public virtual Users Users { get; set; }
    }
}
