//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int ScoreId { get; set; }
        public int UserId { get; set; }
        public int TotalScore { get; set; }
        public int ReachedLevel { get; set; }
        public int RemainingLives { get; set; }
        public Nullable<System.DateTime> PlayedDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
