//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int ScoreId { get; set; }
        public int UserId { get; set; }
        public int TotalScore { get; set; }
        public int ReachedLevel { get; set; }
        public int RemainingLives { get; set; }
        public Nullable<System.DateTime> PlayedDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
